name: Channels Restream

on:
  workflow_dispatch:

jobs:
  restream:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        channel:
          - name: "Magazine"
            id: "CiudadMagazine"
            rtmp_secret_name: "RTMP_SERVER_CANAL1"
            key_secret_name: "STREAM_KEY_CANAL1"

          - name: "QuieroTV"
            id: "Canal2"
            rtmp_secret_name: "RTMP_SERVER_CANAL2"
            key_secret_name: "STREAM_KEY_CANAL2"

          - name: "Metro"
            id: "Canal3"
            rtmp_secret_name: "RTMP_SERVER_CANAL3"
            key_secret_name: "STREAM_KEY_CANAL3"

          - name: "Cronica"
            id: "Cronica"
            rtmp_secret_name: "RTMP_SERVER_CANAL4"
            key_secret_name: "STREAM_KEY_CANAL4"

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Ejecutar Restream (${{ matrix.channel.name }})
        env:
          # Leemos el secret dinámicamente según lo definido en la matriz
          RTMP_SERVER: ${{ secrets[matrix.channel.rtmp_secret_name] }}
          STREAM_KEY: ${{ secrets[matrix.channel.key_secret_name] }}
        run: |
          chmod +x stream.sh
          ./stream.sh "${{ matrix.channel.id }}" "$RTMP_SERVER" "$STREAM_KEY"
