name: Channels Restream

on:
  workflow_dispatch: # Permite iniciar las emisiones manualmente

jobs:
  restream:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Si un canal falla o se corta, los demás siguen transmitiendo
      matrix:
        channel:
          - name: "Magazine"
            id: "CiudadMagazine"
            rtmp_server: "${{ secrets.RTMP_SERVER_CANAL1 }}"
            stream_key: "${{ secrets.STREAM_KEY_CANAL1 }}"

          - name: "elnueve"
            id: "Canal2"
            rtmp_server: "${{ secrets.RTMP_SERVER_CANAL2 }}"
            stream_key: "${{ secrets.STREAM_KEY_CANAL2 }}"

          - name: "Metro"
            id: "Canal3"
            rtmp_server: "${{ secrets.RTMP_SERVER_CANAL3 }}"
            stream_key: "${{ secrets.STREAM_KEY_CANAL3 }}"

          - name: "Cronica"
            id: "Cronica"
            rtmp_server: "${{ secrets.RTMP_SERVER_CANAL4 }}"
            stream_key: "${{ secrets.STREAM_KEY_CANAL4 }}"

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Ejecutar Restream (${{ matrix.channel.name }})
        run: |
          chmod +x stream.sh
          ./stream.sh "${{ matrix.channel.id }}" "${{ matrix.channel.rtmp_server }}" "${{ matrix.channel.stream_key }}"
